### PR TITLE
Fix `is_empty` on receiver and subscriber (#46)

### LINKED ISSUE #46: is_empty on Receiver and Subscriber.
Current is_empty implementation on Receiver and Subscriber only check if wi == 0;

Should be implemented as ri == wi for Receivers and Subscriber. Perhaps add is_receiver_empty on Channel.

### PR DESCRIPTION
**Pull request by stevanmilic**

### CODE REVIEW

File: src/bus/subscriber.rs [hunk 1]
```diff
@@ -37,6 +37,16 @@ impl<T, S: SwapSlot<T>> Subscriber<T, S> {
...
         self.receiver.set_skip_items(skip_items);
     }
+
+    /// Returns the number of remaining in the stream.
+    pub fn len(self) -> usize {
+        self.receiver.len()
+    }
+
+    /// Checks if stream is empty.
+    pub fn is_empty(self) -> bool {
```
Comment (filipdulic) [inline src/bus/subscriber.rs]: passing self as argument assumes you want to consume the object, change to &self

**Review by filipdulic — APPROVED** [review]
